import json
from dataclasses import dataclass, replace
from datetime import datetime, timezone
from pathlib import Path
from typing import Literal

from PIL import Image, ImageDraw

from core.ai_laser_gcode.material_library import DEFAULT_MACHINE_PROFILE_ID, SUPPORTED_VERSION, MaterialRecord, _parse_payload, material_record_key
from core.ai_laser_gcode.models import JobParams, OutputBundle, TaskType
from core.ai_laser_gcode.safety import SafetyError, validate_job_params


CalibrationRating = Literal["good", "cut_through_cleanly", "too_light", "too_dark", "not_cut", "failed"]
SUCCESS_RATINGS = {"good", "cut_through_cleanly"}
ROWS = ("A", "B", "C")
DEFAULT_CELL_MM = 12.0
DEFAULT_GAP_MM = 4.0


@dataclass(frozen=True)
class CalibrationCell:
    cell_id: str
    x_mm: float
    y_mm: float
    size_mm: float
    power: int
    speed: int
    passes: int
    pixel_size_mm: float | None = None
    line_interval_mm: float | None = None


def generate_calibration_matrix(
    material: str,
    output_dir: Path,
    output_format: str = "gcode",
    task_type: TaskType = "engrave_photo",
    thickness_mm: float = 1.0,
    power: int = 120,
    speed: int = 1200,
    passes: int = 1,
    machine_profile_id: str = DEFAULT_MACHINE_PROFILE_ID,
    cell_size_mm: float = DEFAULT_CELL_MM,
    gap_mm: float = DEFAULT_GAP_MM,
    work_area_width_mm: float = 100.0,
    work_area_height_mm: float = 100.0,
) -> OutputBundle:
    cells = build_calibration_cells(task_type, power, speed, passes, cell_size_mm, gap_mm)
    _validate_matrix_bounds(cells, work_area_width_mm, work_area_height_mm)
    for cell in cells:
        params = _cell_params(material, output_format, task_type, thickness_mm, machine_profile_id, work_area_width_mm, work_area_height_mm, cell)
        validate_job_params(params)

    output_dir.mkdir(parents=True, exist_ok=True)
    stem = f"{material}_{task_type}_calibration"
    gcode_path = output_dir / f"{stem}.{output_format}"
    preview_path = output_dir / f"{stem}_preview.png"
    summary_path = output_dir / f"{stem}_summary.json"
    history_path = output_dir / "jobs.jsonl"
    bundle = OutputBundle(gcode_path=gcode_path, preview_path=preview_path, summary_path=summary_path)

    summary = _summary_payload(material, task_type, thickness_mm, machine_profile_id, output_format, cells, bundle)
    try:
        gcode_path.write_text(build_calibration_gcode(material, task_type, cells), encoding="utf-8")
        write_calibration_preview(cells, preview_path, work_area_width_mm, work_area_height_mm)
        summary_path.write_text(json.dumps(summary, ensure_ascii=False, indent=2), encoding="utf-8")
        append_job_history(history_path, {"event": "calibration_matrix_generated", "summary_path": str(summary_path), "calibration_matrix": summary["calibration_matrix"]})
    except Exception:
        for path in (gcode_path, preview_path, summary_path):
            path.unlink(missing_ok=True)
        raise
    return bundle


def build_calibration_cells(task_type: TaskType, power: int, speed: int, passes: int, cell_size_mm: float = DEFAULT_CELL_MM, gap_mm: float = DEFAULT_GAP_MM) -> list[CalibrationCell]:
    power_offsets = (-40, 0, 40)
    speed_offsets = (200, 0, -200)
    cells = []
    for row_index, row in enumerate(ROWS):
        for column_index in range(3):
            cell_power = max(1, min(500, power + power_offsets[column_index]))
            cell_speed = max(300, min(3000, speed + speed_offsets[row_index]))
            cell_passes = passes
            pixel_size_mm = None
            line_interval_mm = None
            if task_type == "cut_contour":
                cell_passes = max(1, min(5, passes + column_index - 1))
            else:
                pixel_size_mm = (0.16, 0.2, 0.24)[column_index]
                line_interval_mm = pixel_size_mm
            cells.append(CalibrationCell(f"{row}{column_index + 1}", column_index * (cell_size_mm + gap_mm), row_index * (cell_size_mm + gap_mm), cell_size_mm, cell_power, cell_speed, cell_passes, pixel_size_mm, line_interval_mm))
    return cells


def build_calibration_gcode(material: str, task_type: TaskType, cells: list[CalibrationCell]) -> str:
    lines = [
        "; Generated by ai-laser-gcode-nc",
        "; Calibration matrix only; observe sample results before saving verified parameters",
        f"; Material: {material}",
        f"; Task type: {task_type}",
        "G21",
        "G90",
        "G94",
        "G17",
        "G92 X0 Y0 Z0",
        "M4 S0",
        "G0 F3000",
    ]
    for cell in cells:
        lines.append(f"; Cell {cell.cell_id}: S{cell.power} F{cell.speed} passes={cell.passes} pixel_size_mm={cell.pixel_size_mm} line_interval_mm={cell.line_interval_mm}")
        for _ in range(cell.passes):
            x0 = cell.x_mm
            y0 = cell.y_mm
            x1 = cell.x_mm + cell.size_mm
            y1 = cell.y_mm + cell.size_mm
            lines.extend(["M5", f"G0 X{x0:.3f} Y{y0:.3f}", "M4 S0"])
            if task_type == "cut_contour":
                lines.extend([f"G1 X{x1:.3f} Y{y0:.3f} S{cell.power} F{cell.speed}", f"G1 X{x1:.3f} Y{y1:.3f} S{cell.power} F{cell.speed}", f"G1 X{x0:.3f} Y{y1:.3f} S{cell.power} F{cell.speed}", f"G1 X{x0:.3f} Y{y0:.3f} S{cell.power} F{cell.speed}"])
            else:
                y = y0
                step = cell.line_interval_mm or 0.2
                while y <= y1 + 1e-9:
                    lines.extend([f"G0 X{x0:.3f} Y{y:.3f}", f"G1 X{x1:.3f} Y{y:.3f} S{cell.power} F{cell.speed}"])
                    y += step
        lines.append("S0")
    lines.extend(["M5", "M2"])
    return "\n".join(lines) + "\n"


def write_calibration_preview(cells: list[CalibrationCell], preview_path: Path, work_area_width_mm: float, work_area_height_mm: float) -> None:
    scale = 4
    image = Image.new("RGB", (int(work_area_width_mm * scale), int(work_area_height_mm * scale)), "white")
    draw = ImageDraw.Draw(image)
    for cell in cells:
        box = [int(cell.x_mm * scale), int(cell.y_mm * scale), int((cell.x_mm + cell.size_mm) * scale), int((cell.y_mm + cell.size_mm) * scale)]
        draw.rectangle(box, outline="black", width=2)
        draw.text((box[0] + 3, box[1] + 3), cell.cell_id, fill="black")
    image.save(preview_path)


def save_calibration_result(summary_path: Path, cell_id: str, rating: CalibrationRating, material_library_path: Path, jobs_path: Path | None = None) -> bool:
    summary = json.loads(summary_path.read_text(encoding="utf-8"))
    matrix = summary.get("calibration_matrix", {})
    cells = matrix.get("cells", {})
    if cell_id not in cells:
        raise ValueError(f"Unknown calibration cell id: {cell_id}")
    selected = cells[cell_id]
    history_path = jobs_path or summary_path.parent / "jobs.jsonl"
    append_job_history(history_path, {"event": "calibration_result_recorded", "summary_path": str(summary_path), "cell_id": cell_id, "rating": rating, "parameters": selected})
    if rating not in SUCCESS_RATINGS:
        return False
    record = MaterialRecord(
        machine_profile_id=str(summary["machine_profile_id"]),
        material=str(summary["material"]),
        thickness_mm=float(summary["thickness_mm"]),
        task_type=summary["task_type"],
        confidence="verified",
        mode="raster" if summary["task_type"] == "engrave_photo" else "outline",
        speed=int(selected["speed"]),
        power=int(selected["power"]),
        passes=int(selected["passes"]),
        source="user_verified_calibration",
        pixel_size_mm=selected.get("pixel_size_mm"),
        line_interval_mm=selected.get("line_interval_mm"),
    )
    upsert_verified_material_record(material_library_path, record)
    return True


def upsert_verified_material_record(path: Path, record: MaterialRecord) -> None:
    if path.exists():
        payload = json.loads(path.read_text(encoding="utf-8"))
        records = {material_record_key(existing): existing for existing in _parse_payload(payload)}
    else:
        records = {}
    records[material_record_key(record)] = record
    materials = [_material_record_payload(existing) for existing in records.values()]
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps({"version": SUPPORTED_VERSION, "materials": materials}, ensure_ascii=False, indent=2), encoding="utf-8")


def append_job_history(path: Path, payload: dict[str, object]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    record = {"created_at": datetime.now(timezone.utc).isoformat(), **payload}
    with path.open("a", encoding="utf-8") as handle:
        handle.write(json.dumps(record, ensure_ascii=False, separators=(",", ":")) + "\n")


def _summary_payload(material: str, task_type: TaskType, thickness_mm: float, machine_profile_id: str, output_format: str, cells: list[CalibrationCell], bundle: OutputBundle) -> dict[str, object]:
    return {
        "contract_version": 1,
        "job_type": "calibration_matrix",
        "material": material,
        "thickness_mm": thickness_mm,
        "task_type": task_type,
        "machine_profile_id": machine_profile_id,
        "output_format": output_format,
        "can_send": False,
        "next_action": "run_sample_test",
        "message": "校准矩阵仅用于小样测试，请观察结果后显式保存成功参数。",
        "files": {"gcode": str(bundle.gcode_path), "preview": str(bundle.preview_path), "summary": str(bundle.summary_path)},
        "calibration_matrix": {"rows": 3, "columns": 3, "cells": {cell.cell_id: _cell_payload(cell) for cell in cells}},
    }


def _cell_payload(cell: CalibrationCell) -> dict[str, object]:
    return {"power": cell.power, "speed": cell.speed, "passes": cell.passes, "pixel_size_mm": cell.pixel_size_mm, "line_interval_mm": cell.line_interval_mm}


def _cell_params(material: str, output_format: str, task_type: TaskType, thickness_mm: float, machine_profile_id: str, work_area_width_mm: float, work_area_height_mm: float, cell: CalibrationCell) -> JobParams:
    mode = "raster" if task_type == "engrave_photo" else "outline"
    return JobParams(material=material, size_mm=cell.size_mm, power=cell.power, feed_rate=cell.speed, output_format=output_format, mode=mode, pixel_size_mm=cell.pixel_size_mm or 0.2, work_area_width_mm=work_area_width_mm, work_area_height_mm=work_area_height_mm, thickness_mm=thickness_mm, thickness_source="explicit", task_type=task_type, task_type_source="explicit", machine_profile_id=machine_profile_id, passes=cell.passes, can_send=False, next_action="run_sample_test")


def _validate_matrix_bounds(cells: list[CalibrationCell], work_area_width_mm: float, work_area_height_mm: float) -> None:
    if not cells:
        raise SafetyError("Calibration matrix must contain at least one cell")
    max_x = max(cell.x_mm + cell.size_mm for cell in cells)
    max_y = max(cell.y_mm + cell.size_mm for cell in cells)
    if max_x > work_area_width_mm * 0.8 or max_y > work_area_height_mm * 0.8:
        raise SafetyError("Calibration matrix must fit conservatively within the work area")


def _material_record_payload(record: MaterialRecord) -> dict[str, object]:
    payload = {
        "machine_profile_id": record.machine_profile_id,
        "material": record.material,
        "thickness_mm": record.thickness_mm,
        "task_type": record.task_type,
        "confidence": record.confidence,
        "mode": record.mode,
        "speed": record.speed,
        "power": record.power,
        "passes": record.passes,
        "source": record.source,
    }
    if record.pixel_size_mm is not None:
        payload["pixel_size_mm"] = record.pixel_size_mm
    if record.line_interval_mm is not None:
        payload["line_interval_mm"] = record.line_interval_mm
    return payload
