import math
from dataclasses import replace

from core.ai_laser_gcode.models import GcodeOutputStats, JobParams, RasterResult, TraceResult


def build_gcode(
    params: JobParams,
    trace: TraceResult,
    *,
    auto_close_open_paths: bool = True,
    contour_start_dwell_s: float = 0.0,
    travel_mode: str = "rapid_g0",
) -> str:
    gcode, _ = build_gcode_with_stats(
        params,
        trace,
        auto_close_open_paths=auto_close_open_paths,
        contour_start_dwell_s=contour_start_dwell_s,
        travel_mode=travel_mode,
    )
    return gcode


def build_gcode_with_stats(
    params: JobParams,
    trace: TraceResult,
    *,
    auto_close_open_paths: bool = True,
    contour_start_dwell_s: float = 0.0,
    travel_mode: str = "rapid_g0",
) -> tuple[str, GcodeOutputStats]:
    """Build outline G-code.

    Optional keyword-only hooks default to production behavior:
    - auto_close_open_paths=True keeps the historical close-to-start burn
    - contour_start_dwell_s=0.0 inserts no G4
    - travel_mode="rapid_g0" keeps path-start G0 travel
    Offline candidates may opt into controlled travel / dwell without changing
    production call sites (which pass no kwargs).
    """
    if travel_mode not in {"rapid_g0", "controlled_g1_s0"}:
        raise ValueError(f"Unsupported travel_mode {travel_mode!r}")
    try:
        dwell_seconds = float(contour_start_dwell_s)
    except (TypeError, ValueError) as error:
        raise ValueError("contour_start_dwell_s must be a finite non-negative number") from error
    if dwell_seconds < 0 or not math.isfinite(dwell_seconds):
        raise ValueError("contour_start_dwell_s must be a finite non-negative number")

    lines = [
        "; Generated by ai-laser-gcode-nc",
        "; GRBL laser mode expected: $30=1000, $32=1",
        f"; Material: {params.material}; note: {params.safety_note}",
        "G21",
        "G90",
        "G94",
        "G17",
        "G92 X0 Y0 Z0",
        f"{params.laser_mode} S0",
        "G0 F3000",
    ]
    stats = GcodeOutputStats(arc_enabled=params.arc_output, arc_supported=params.firmware_supports_arc)
    for path in trace.paths:
        if not path:
            continue
        machine_path = _trace_path_to_machine_coords(path, trace.height_mm)
        start_x, start_y = machine_path[0]
        lines.append("M5")
        if travel_mode == "controlled_g1_s0":
            lines.append(f"{params.laser_mode} S0")
            lines.append(f"G1 X{start_x:.3f} Y{start_y:.3f} S0 F{params.feed_rate}")
        else:
            lines.append(f"G0 X{start_x:.3f} Y{start_y:.3f}")
            lines.append(f"{params.laser_mode} S0")
        if dwell_seconds > 0:
            # GRBL dwell in seconds: G4 P0.15
            dwell_text = f"{dwell_seconds:.3f}".rstrip("0").rstrip(".")
            lines.append(f"G4 P{dwell_text}")
        path_lines, path_stats = _build_path_motion_lines(params, machine_path)
        lines.extend(path_lines)
        stats = _merge_stats(stats, path_stats)
        if auto_close_open_paths and len(machine_path) > 2 and machine_path[-1] != machine_path[0]:
            lines.append(f"G1 X{start_x:.3f} Y{start_y:.3f} S{params.power} F{params.feed_rate}")
            stats = _merge_stats(stats, GcodeOutputStats(params.arc_output, params.firmware_supports_arc, line_segment_count=1))
        lines.append("S0")
    lines.extend(["M5", "M2"])
    return "\n".join(lines) + "\n", stats


def _trace_path_to_machine_coords(path: list[tuple[float, float]], height_mm: float) -> list[tuple[float, float]]:
    return [(x_coord, height_mm - y_coord) for x_coord, y_coord in path]


def _build_path_motion_lines(params: JobParams, path: list[tuple[float, float]]) -> tuple[list[str], GcodeOutputStats]:
    stats = GcodeOutputStats(params.arc_output, params.firmware_supports_arc)
    if not params.arc_output or not params.firmware_supports_arc:
        lines = [_g1_line(params, x_coord, y_coord) for x_coord, y_coord in path[1:]]
        return lines, _merge_stats(stats, GcodeOutputStats(params.arc_output, params.firmware_supports_arc, line_segment_count=len(lines)))
    fit_path = path[:-1] if len(path) > 2 and path[0] == path[-1] else path
    arc = _fit_arc(fit_path, params.arc_tolerance_mm)
    if arc is None:
        lines = [_g1_line(params, x_coord, y_coord) for x_coord, y_coord in path[1:]]
        fallback_count = max(0, len(path) - 1)
        return lines, _merge_stats(stats, GcodeOutputStats(params.arc_output, params.firmware_supports_arc, line_segment_count=len(lines), fallback_segment_count=fallback_count))
    end_x, end_y = fit_path[-1]
    lines = [f"{arc.gcode} X{end_x:.3f} Y{end_y:.3f} I{arc.i_offset:.3f} J{arc.j_offset:.3f} S{params.power} F{params.feed_rate}"]
    line_segment_count = 0
    if fit_path is not path:
        start_x, start_y = path[0]
        lines.append(_g1_line(params, start_x, start_y))
        line_segment_count = 1
    return lines, _merge_stats(stats, GcodeOutputStats(params.arc_output, params.firmware_supports_arc, arc_count=1, line_segment_count=line_segment_count))


def _g1_line(params: JobParams, x_coord: float, y_coord: float) -> str:
    return f"G1 X{x_coord:.3f} Y{y_coord:.3f} S{params.power} F{params.feed_rate}"


class _ArcFit:
    def __init__(self, gcode: str, i_offset: float, j_offset: float):
        self.gcode = gcode
        self.i_offset = i_offset
        self.j_offset = j_offset


def _fit_arc(path: list[tuple[float, float]], tolerance_mm: float) -> _ArcFit | None:
    if len(path) < 4:
        return None
    start = path[0]
    middle = path[len(path) // 2]
    end = path[-1]
    center = _circle_center(start, middle, end)
    if center is None:
        return None
    center_x, center_y = center
    radius = math.hypot(start[0] - center_x, start[1] - center_y)
    if not math.isfinite(radius) or radius < 0.5:
        return None
    for x_coord, y_coord in path:
        radial_error = abs(math.hypot(x_coord - center_x, y_coord - center_y) - radius)
        if radial_error > tolerance_mm:
            return None
    direction = _arc_direction(start, middle, end)
    if direction == 0:
        return None
    return _ArcFit("G3" if direction > 0 else "G2", center_x - start[0], center_y - start[1])


def _circle_center(a: tuple[float, float], b: tuple[float, float], c: tuple[float, float]) -> tuple[float, float] | None:
    ax, ay = a
    bx, by = b
    cx, cy = c
    determinant = 2 * (ax * (by - cy) + bx * (cy - ay) + cx * (ay - by))
    if abs(determinant) < 1e-9:
        return None
    ux = ((ax * ax + ay * ay) * (by - cy) + (bx * bx + by * by) * (cy - ay) + (cx * cx + cy * cy) * (ay - by)) / determinant
    uy = ((ax * ax + ay * ay) * (cx - bx) + (bx * bx + by * by) * (ax - cx) + (cx * cx + cy * cy) * (bx - ax)) / determinant
    if not math.isfinite(ux) or not math.isfinite(uy):
        return None
    return ux, uy


def _arc_direction(start: tuple[float, float], middle: tuple[float, float], end: tuple[float, float]) -> int:
    cross = (middle[0] - start[0]) * (end[1] - start[1]) - (middle[1] - start[1]) * (end[0] - start[0])
    if abs(cross) < 1e-9:
        return 0
    return 1 if cross > 0 else -1


def _merge_stats(left: GcodeOutputStats, right: GcodeOutputStats) -> GcodeOutputStats:
    return GcodeOutputStats(
        arc_enabled=left.arc_enabled or right.arc_enabled,
        arc_supported=left.arc_supported or right.arc_supported,
        arc_count=left.arc_count + right.arc_count,
        line_segment_count=left.line_segment_count + right.line_segment_count,
        fallback_segment_count=left.fallback_segment_count + right.fallback_segment_count,
    )


def build_raster_gcode(params: JobParams, raster: RasterResult) -> str:
    raster = _raster_to_machine_coords(raster)
    lines = [
        "; Generated by ai-laser-gcode-nc",
        "; GRBL laser mode expected: $30=1000, $32=1",
        f"; Material: {params.material}; note: {params.safety_note}",
        "; Raster mode: black/white dithered scan",
        "G21",
        "G90",
        "G94",
        "G17",
        "G92 X0 Y0 Z0",
        f"{params.laser_mode} S0",
        "G0 F3000",
    ]
    if raster.output_strategy == "scanline":
        for line_index, segments in enumerate(_raster_scanline_groups(raster)):
            lines.extend(_raster_scanline_lines(params, raster, segments, line_index))
    else:
        for segment in raster.segments:
            lines.extend(_raster_segment_lines(params, raster, segment))
    lines.extend(["M5", "M2"])
    return "\n".join(lines) + "\n"


def _raster_to_machine_coords(raster: RasterResult) -> RasterResult:
    return replace(
        raster,
        segments=[_raster_segment_to_machine_coords(segment, raster) for segment in raster.segments],
    )


def _raster_segment_to_machine_coords(segment, raster: RasterResult):
    if segment.axis == "vertical":
        return replace(
            segment,
            y_mm=max(0.0, raster.height_mm - segment.end_y_mm),
            end_y_mm=max(0.0, raster.height_mm - segment.y_mm),
        )
    return replace(
        segment,
        y_mm=max(0.0, raster.height_mm - raster.pixel_size_mm - segment.y_mm),
    )


def _raster_segment_lines(params: JobParams, raster: RasterResult, segment) -> list[str]:
    if segment.axis == "vertical":
        start_y = segment.y_mm + raster.overscan_mm
        end_y = segment.end_y_mm + raster.overscan_mm
        overscan_start = max(0.0, start_y - raster.overscan_mm)
        overscan_end = min(raster.work_area_height_mm, end_y + raster.overscan_mm)
        return [
            "M5",
            f"G0 X{segment.start_x_mm:.3f} Y{overscan_start:.3f}",
            f"{params.laser_mode} S0",
            f"G1 Y{start_y:.3f} F{params.feed_rate} S0",
            f"G1 Y{end_y:.3f} S{params.power} F{params.feed_rate}",
            f"G1 Y{overscan_end:.3f} S0",
        ]
    start_x = segment.start_x_mm + raster.overscan_mm
    end_x = segment.end_x_mm + raster.overscan_mm
    overscan_start = max(0.0, start_x - raster.overscan_mm)
    overscan_end = min(raster.work_area_width_mm, end_x + raster.overscan_mm)
    return [
        "M5",
        f"G0 X{overscan_start:.3f} Y{segment.y_mm:.3f}",
        f"{params.laser_mode} S0",
        f"G1 X{start_x:.3f} F{params.feed_rate} S0",
        f"G1 X{end_x:.3f} S{params.power} F{params.feed_rate}",
        f"G1 X{overscan_end:.3f} S0",
    ]


def _raster_scanline_groups(raster: RasterResult) -> list[list]:
    if raster.scan_direction == "vertical":
        sorted_segments = sorted(raster.segments, key=lambda segment: (segment.start_x_mm, segment.y_mm, segment.end_y_mm))
        return _group_scanline_segments(sorted_segments, lambda segment: segment.start_x_mm)
    sorted_segments = sorted(raster.segments, key=lambda segment: (segment.y_mm, segment.start_x_mm, segment.end_x_mm))
    return _group_scanline_segments(sorted_segments, lambda segment: segment.y_mm)


def _group_scanline_segments(segments, key_fn) -> list[list]:
    groups: list[list] = []
    current_key: float | None = None
    for segment in segments:
        key = key_fn(segment)
        if current_key is None or abs(key - current_key) > 1e-9:
            groups.append([])
            current_key = key
        groups[-1].append(segment)
    return groups


def _raster_scanline_lines(params: JobParams, raster: RasterResult, segments, line_index: int) -> list[str]:
    if not segments:
        return []
    reverse = raster.snake_scan and line_index % 2 == 1
    if segments[0].axis == "vertical":
        return _vertical_scanline_lines(params, raster, segments, reverse)
    return _horizontal_scanline_lines(params, raster, segments, reverse)


def _horizontal_scanline_lines(params: JobParams, raster: RasterResult, segments, reverse: bool) -> list[str]:
    y_coord = segments[0].y_mm
    shifted_runs = [(segment.start_x_mm + raster.overscan_mm, segment.end_x_mm + raster.overscan_mm) for segment in segments]
    scan_start = max(0.0, min(start for start, _ in shifted_runs) - raster.overscan_mm)
    scan_end = min(raster.work_area_width_mm, max(end for _, end in shifted_runs) + raster.overscan_mm)
    if reverse:
        lines = ["M5", f"G0 X{scan_end:.3f} Y{y_coord:.3f}", f"{params.laser_mode} S0"]
        for start_x, end_x in reversed(shifted_runs):
            lines.append(f"G1 X{end_x:.3f} F{params.feed_rate} S0")
            lines.append(f"G1 X{start_x:.3f} S{params.power} F{params.feed_rate}")
        lines.append(f"G1 X{scan_start:.3f} S0")
        return lines
    lines = ["M5", f"G0 X{scan_start:.3f} Y{y_coord:.3f}", f"{params.laser_mode} S0"]
    for start_x, end_x in shifted_runs:
        lines.append(f"G1 X{start_x:.3f} F{params.feed_rate} S0")
        lines.append(f"G1 X{end_x:.3f} S{params.power} F{params.feed_rate}")
    lines.append(f"G1 X{scan_end:.3f} S0")
    return lines


def _vertical_scanline_lines(params: JobParams, raster: RasterResult, segments, reverse: bool) -> list[str]:
    x_coord = segments[0].start_x_mm
    shifted_runs = [(segment.y_mm + raster.overscan_mm, segment.end_y_mm + raster.overscan_mm) for segment in segments]
    scan_start = max(0.0, min(start for start, _ in shifted_runs) - raster.overscan_mm)
    scan_end = min(raster.work_area_height_mm, max(end for _, end in shifted_runs) + raster.overscan_mm)
    if reverse:
        lines = ["M5", f"G0 X{x_coord:.3f} Y{scan_end:.3f}", f"{params.laser_mode} S0"]
        for start_y, end_y in reversed(shifted_runs):
            lines.append(f"G1 Y{end_y:.3f} F{params.feed_rate} S0")
            lines.append(f"G1 Y{start_y:.3f} S{params.power} F{params.feed_rate}")
        lines.append(f"G1 Y{scan_start:.3f} S0")
        return lines
    lines = ["M5", f"G0 X{x_coord:.3f} Y{scan_start:.3f}", f"{params.laser_mode} S0"]
    for start_y, end_y in shifted_runs:
        lines.append(f"G1 Y{start_y:.3f} F{params.feed_rate} S0")
        lines.append(f"G1 Y{end_y:.3f} S{params.power} F{params.feed_rate}")
    lines.append(f"G1 Y{scan_end:.3f} S0")
    return lines
